[programs.localnet]
mysolanaapp = "2mVaCE7vC289j6zMpXzGLa3i57BBt5LYSQifrzS6LXXv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/vitor/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
